apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ekart-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: prashantphad45/ekart
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/prune: "true"
spec:
  project: default
  source:
    repoURL: https://github.com/prashant169/Ekart.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
