# --------------------------------------------
# Kubernetes Deployment for Ekart Application
# --------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
  labels:
    app: ekart
spec:
  replicas: 2  # Run 2 pods
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
        - name: ekart
          image: prashantphad45/ekart:20250704133122
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070   # The port your Spring Boot app runs on
          readinessProbe:           # ✅ Optional: Helps determine when the pod is ready to serve traffic
            httpGet:
              path: /
              port: 8070
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:            # ✅ Optional: Ensures container is alive and responsive
            httpGet:
              path: /
              port: 8070
            initialDelaySeconds: 15
            periodSeconds: 10

---

# --------------------------------------------
# Kubernetes Service for Ekart Application
# --------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: ekart-ssvc
  labels:
    app: ekart
spec:
  selector:
    app: ekart
  type: NodePort #type: LoadBalancer  #  Will expose your app outside the cluster (if supported by your environment)
  ports:
    - name: http
      protocol: TCP
      port: 8070         # The port exposed by the service
      targetPort: 8070   # The port your app container listens on
